version: '3.8'
services: 
  app:
    container_name: api
    build: .
    image: apiimage
    restart: always
    ports: 
      - 8000:8000
    command: bash -c "cd app && python -m uvicorn task:app --reload --host 0.0.0.0 --port 8000"

